version: '3.8'

services:
  node_app:
    container_name: node_app
    image: node_app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - 7777:7777
    networks:
      - moderator-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  moderator-network:
    driver: bridge
